<?php if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<hr />
<p class="credits">
    <a href="https://github.com/AndiDittrich/WordPress.Cryptex/">Cryptex</a> <?php _e('is developed by', 'cryptex'); ?> <a href="https://andidittrich.de">Andi Dittrich</a>.
    <?php printf(__('It`s released under the terms of the %s', 'cryptex'), '<a href="#TB_inline?width=800&height=550&inlineId=cryptex-license" class="thickbox">'.__('GPL-2.0', 'cryptex').'</a>'); ?><br />
    <strong><?php _e('Includes:', 'cryptex'); ?></strong>
    <a href="https://fedorahosted.org/liberation-fonts/">Liberation(tm) Fonts</a> SIL Open Font License, Version 1.1
    | <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> <?php _e('by', 'cryptex'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> - MPL 2.0 <?php _e('License', 'cryptex'); ?>;
</p>
<hr />