<div id="CryptexHelp" style="display: none;">
<p><?php _e('Just insert a email-address surrounded by cryptex shortcode into your post! - That`s it!'); ?></p>

<h2><?php _e('Shortcodes'); ?></h2>
<p><?php _e('Cryptex provides two shortcodes for interoperable usage. Both are doing exactly the same!'); ?></p>

<h4><?php _e('Example - Standard'); ?></h4>
<pre>
[email]my.address@example.com[/email]
</pre>

<p><?php _e('To avoid namespace collisions with other plugins, you can disable the <code>[email]</code> shortcode alias (advanced settings, bottom of the page).'); ?><br />
<?php _e('In this case you can still use the cryptex plugin with the following legacy shortcode (already used by plugin version 1+2):'); ?></p>

<h4><?php _e('Example - Legacy Shortcode'); ?></h4>
<pre>
[cryptex]my.address@example.com[/cryptex]
</pre>

</div>