<?php
if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED');

// check
if (function_exists('gd_info')){
		echo '<p>';
		$info = gd_info();
		echo __('GD lib installed:'), '<strong style="color:#090">', __('true'), '</strong><br />';	
		echo __('GD version:'), ' <strong style="color:#090">',  $info["GD Version"],'</strong><br />';	
		
		// png support
		if ($info['PNG Support']){
			echo __('PNG support:'), ' <strong style="color:#090">', __('true'), '</strong><br />';
		}else{
			echo __('PNG support:'), ' <strong style="color:#900">', __('false'), '</strong><br />';
		}
		
		// font path avaible ?
		if (is_dir(get_option('cryptex-font-path', CRYPTEX_DEFAULT_FONT_PATH))){
			echo __('System font path:'), ' <strong style="color:#090">', __('valid'), '</strong><br />';
		}else{
			echo __('System font path:'), ' <strong style="color:#900">', __('invalid'), '</strong><br />';
		}
		
		// fonts avaible ?
		if (count($fonts)>0){
			echo __('Fonts avaible:'), ' <strong style="color:#090">', __('true'), '</strong><br />';
		}else{
			echo __('Fonts avaible:'), ' <strong style="color:#900">', __('false - fallback active'), '</strong><br />';
		}

		// PHP version
		if (version_compare(phpversion(), '5.0', '>=')){
			echo __('PHP version:'), ' <strong style="color:#090">', phpversion() ,'</strong><br />';
		}else{
			echo __('PHP version:'), ' <strong style="color:#900">', phpversion() ,'</strong><br />';
		}

		// server os
		echo __('Server OS:'), ' <strong>', PHP_OS,'</strong><br />';
				
		// cryptex version
		echo __('Cryptex Plugin Version:'), ' <strong>', CRYPTEX_VERSION, '</strong><br />';
		
		echo '</p>';
	}else{
		echo '<div class="updated error"><p><strong>', __('GD library not found on your system - you cannot use cryptex until you or your hosting provider install the GD library with enabled PNG support'), '</strong></p></div>';
	}
?>