<?php if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="postbox">
<h3 class="hndle"><?php _e('Cryptex Related', 'cryptex'); ?></h3>
<div class="inside">
<!-- Metabox-Content -->
	<p><?php _e('Got a problem ? Need support or want to request a new feature ?', 'cryptex'); ?></p>
	<ul>
		<li><a href="http://wordpress.org/support/plugin/cryptex"><?php _e('Support Forum', 'cryptex'); ?></a></li>
    	<li><a href="https://github.com/AndiDittrich/WordPress.Cryptex"><?php _e('Cryptex on GitHub', 'cryptex'); ?></a></li>
		<li><a href="http://wordpress.org/plugins/cryptex/"><?php _e('Cryptex on WordPress.org', 'cryptex'); ?></a></li>
		<li><a href="https://github.com/AndiDittrich/WordPress.Cryptex/issues"><?php _e('Report a Bug', 'cryptex'); ?></a></li>
		<li><a href="http://andidittrich.de/"><?php _e('Author`s Website', 'cryptex'); ?></a></li>
	</ul>
<!-- // Metabox-Content -->
</div></div>