<?php
/**
	Descriptionn: Cryptex Admin Settings Page
	Plugin URI: http://andidittrich.de/go/cryptex
	Version: 4.0
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013-2014, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>
<?php add_thickbox(); ?>

<!-- CryptexSettings:wrap -->
<div class="wrap" id="CryptexSettings">

<!-- Settings Tabs -->
<h2 class="nav-tab-wrapper" id="CryptexTabNav">
	<a data-tab="CryptexTabAppearance" class="nav-tab"><?php _e('Appearance', 'cryptex'); ?></a>
	<a data-tab="CryptexTabOptions" class="nav-tab"><?php _e('Options', 'cryptex'); ?></a>
	<a data-tab="CryptexTabAdvanced" class="nav-tab"><?php _e('Advanced', 'cryptex'); ?></a>
</h2>

<!-- Main Title -->
<h2 class="maintitle"><?php _e('Cryptex | E-Mail-Address Protection', 'cryptex'); ?></h2>
<p><strong><?php _e('Howto:', 'cryptex'); ?> </strong><?php _e('Just insert a email-address surrounded by cryptex shortcode into your post! Example:', 'cryptex'); ?> <strong>[email]your.address@yourdomain.tld[/email]</strong></p>

<!-- settings !-->
<form method="post" action="options.php">
	<?php settings_fields('cryptex-settings-group' ); ?>
	<!-- #poststuff -->
	<div id="poststuff">

<!-- 2 Column Layout -->
<div id="post-body" class="metabox-holder columns-2">
	<div id="post-body-content">
	 
		<div id="CryptexTabAppearance">
		<?php require ('Appearance.phtml'); ?>
		</div>
		
		<div id="CryptexTabOptions">
		<?php require ('Options.phtml'); ?>
		</div>
		
		<div id="CryptexTabAdvanced">
		<?php require ('Advanced.phtml'); ?>
		</div>
		
		<!-- submit !-->
	    <?php submit_button(); ?>

    </div>
    <!-- // MAIN COLUMN -->
	
	<!-- Right Column -->
	<div id="postbox-container-1" class="postbox-container">
		<?php require('SystemInfo.phtml'); ?>
		
		<?php require('Related.phtml'); ?>
	</div>
	<!-- // Right Column -->
	
</div>
<!-- // 2 Column Layout -->

</div>
<!-- // #poststuff -->

</form>
<div class="clear"></div>
<hr />
<p class="credits">
    <a href="http://andidittrich.de/go/cryptex">Cryptex</a> <?php _e('is developed by', 'cryptex'); ?> <a href="http://andidittrich.de">Andi Dittrich</a>.
    <?php printf(__('It`s released under the terms of the %s', 'cryptex'), '<a href="#TB_inline?width=800&height=550&inlineId=cryptex-license" class="thickbox">'.__('MIT X11 License', 'cryptex').'</a>'); ?>
    | <strong><?php _e('Includes:', 'cryptex'); ?></strong> <a href="http://www.eyecon.ro/colorpicker/">Colorpicker</a> <?php _e('by', 'cryptex'); ?> <a href="http://www.eyecon.ro">Stefan Petre</a> - MIT/GPL <?php _e('License', 'cryptex'); ?>
    | <a href="https://fedorahosted.org/liberation-fonts/">Liberation(tm) Fonts</a>  SIL Open Font License, Version 1.1
    | <a href="https://github.com/carhartl/jquery-cookie">jquery.cookie</a> <?php _e('by', 'cryptex'); ?> <a href="https://twitter.com/carhartl">Klaus Hartl</a> - MIT <?php _e('License', 'cryptex'); ?>;
</p>

<?php require('License.phtml'); ?>

</div>
<!-- // CryptexSettings:wrap -->

<div class="clear"></div>