<?php
/**
	Descriptionn: Enlighter Admin Settings Page
	Plugin URI: http://www.a3non.org/go/enlighterjs
	Version: 1.2
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="wrap">
<div id="icon-options-general" class="icon32"><br /></div>
<h2><?php _e('Cryptex | E-Mail-Address Protection'); ?></h2>


<!-- Breadcrumb -->
<?php add_thickbox(); ?>
<div id='setting-error-settings_updated' class='updated settings-error'> 
<p><strong><?php _e('Cryptex related:'); ?> </strong>
	<a href="#TB_inline?height=500&width=800&inlineId=CryptexHelp" class="thickbox" rel="Cryptex Help"><?php _e('View Help'); ?></a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Cryptex"><?php _e('Cryptex on GitHub'); ?></a> | 
	<a href="http://wordpress.org/plugins/cryptex/"><?php _e('Cryptex on WordPress.org'); ?></a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Cryptex/issues"><?php _e('Report a Bug'); ?></a>
</p>
<p><strong><?php _e('Howto:'); ?> </strong><?php _e('Just insert a email-address surrounded by cryptex shortcode into your post! Example: <strong>'); ?>[email]your.address@yourdomain.tld[/email]</strong></p>
</div>

<!-- Help Overlay Content -->
<?php require('Help.phtml'); ?>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('cryptex-settings-group' ); ?>
    
    <!-- System Info -->
    <h3><?php _e('System Info'); ?></h3>
    <div class="CryptexBlockcontent">
    <ul> 
    	<?php 
    	// PHP version
    	if (version_compare(phpversion(), '5.3', '>=')){
    		echo '<li>', __('PHP Version:'), ' <span class="CryptexTRUE">', phpversion() , '</span></li>';
    	}else{
    		echo '<li>', __('PHP Version:'), ' <span class="CryptexFALSE">', phpversion() ,'</span></li>';
    	}
    	
    	// server os
    	echo '<li>', __('Server Software:'), ' <span class="CryptexTRUE">', PHP_OS, '</span></li>';
    	
    	// cryptex version
    	echo '<li>', __('Cryptex Plugin Version:'), ' <span class="CryptexTRUE">', CRYPTEX_VERSION, '</span></li>';
    	
    	// check for gdlib
    	if (function_exists('gd_info')){
    		echo '<li>', __('GD library installed:'), ' <span class="CryptexTRUE">', __('true'), '</span></li>';
    		$info = gd_info(); 

    		// check GD lib version
   			echo '<li>', __('GD version:'), ' <span class="CryptexTRUE">',  $info['GD Version'], __(' (supported)'), '</span></li>';
    		
    		// check png support
    		if ($info['PNG Support']){
    			echo '<li>', __('PNG support:'), ' <span class="CryptexTRUE">', __('true'), '</span></li>';
    		}else{
    			echo '<li>', __('PNG support:'), ' <span class="CryptexFALSE">', __('false'), '</span></li>';
    		}
    		
    	}else{
    		echo '<li>', __('GD library installed:'), ' <span class="CryptexFALSE">', __('false'), '</span></li>';
    	}
    	
    	// check for available fonts
    	if (count($fontlist)>0){    	
    		echo '<li>', 'Fonts available (within selected directory): <span class="CryptexTRUE">', __('true'), '</span></li>';	
    	}else{
    		echo '<li>', 'Fonts available (within selected directory): <span class="CryptexFALSE">', __('false'), '</span></li>';
    	}
    	
    	// plugin cache path writeable ?
    	$cachePath = CRYPTEX_PLUGIN_PATH.DIRECTORY_SEPARATOR.'cache';
    	if (is_dir($cachePath) && is_writable($cachePath)){
    		echo '<li>', __('Cache writeable'),' (<code>', $cachePath ,'</code>): <span class="CryptexTRUE">', __('true'), '</span></li>';
    	}else{
    		echo '<li>', __('Cache writeable'),' (<code>', $cachePath ,'</code>): <span class="CryptexFALSE">', __('false'), '</span></li>';
    	}
    	?>
    </ul>	
    </div>
    
    <!-- System Font Source -->
    <h3><?php _e('Font Source'); ?></h3>
    <div class="CryptexBlockcontent">
        <p><?php _e('Cryptex requires server-side stored TrueTypeFonts to generate the images. Select the font location which should be used - only <strong>.ttf</strong> files are supported! The location will be recursivly scanned by the plugin (including all subdirectories).'); ?></p>
   		<p>
		<?php _e('<strong>System Fonts</strong> - the default font location of your server'); ?> (<code><?php echo implode(';', Cryptex\FontManager::$WindowsFontPaths); ?></code> <?php _e('on Windows'); ?>; <code><?php echo implode(';', Cryptex\FontManager::$LinuxFontPaths); ?></code> <?php _e('on Linux'); ?><br />
		<?php _e('<strong>Plugin Directory</strong> - the <code>fonts</code> directory within the cryptex plugin path'); ?> (<code><?php echo CRYPTEX_DEFAULT_FONT_PATH ?></code>)<br />
		<?php _e('<strong>Custom Directory</strong> - enter a custom directory of your choice'); ?>
		</p>
		<!-- Font Source -->
		<?php $this->_settingsUtility->displaySelect('Font-Source', 'font-source', array('System Fonts' => 'system', 'Plugin Directory' => 'plugin', 'Custom Directory' => 'custom')); ?>
		
		<!-- Custom Font Path -->
		<div id="CryptexCustomFontpath">
		<?php $this->_settingsUtility->displayInput('Font-Path', 'custom-font-path', 'e.g. <code>/usr/share/fonts</code>'); ?>
		</div>
		
		<input name="submit" id="CryptexApplyChanges" class="button button-primary" value="Apply Changes" type="submit" />
	</div>
    
	<!-- appearance !-->
    <h3><?php _e('Appearance'); ?></h3>
    <div class="CryptexBlockcontent">
		<p><?php _e('Change these settings to match your current theme styles.'); ?> <br />
		<?php _e('<strong>Note: </strong>It`s strongly recommend to use standard fonts only - otherwise it could cause problems by displaying them on clients which have not installed these custom fonts yet.'); ?>
		</p>

		<!-- Font List -->
		<?php $this->_settingsUtility->displaySelect('Font-Family', 'font-file', $fontlist); ?>
		
		<!-- Font Size -->
		<?php $this->_settingsUtility->displayInput('Font-Size (px)', 'font-size', 'e.g. 12'); ?>
		
		<!-- Font Color -->
		<?php $this->_settingsUtility->displayInput('Font-Color', 'font-color', 'e.g. #000000, #ff00c1', 'CryptexColorChooser'); ?>
		
		<!-- @ replacement -->
    	<p><?php _e('Instead of using the @ sign for emails, you can choose between some options - this could increase the protection level against spiders/bots using OCR.'); ?>				
  	 	<br /><?php _e('<strong>Note:</strong> Use ALWAYS the @ sign in the cryptex shortcode!'); ?></p>
		<?php $this->_settingsUtility->displaySelect('@Sign-Replacement', 'email-divider', array('@' => '@', '(at)' => '(at)', '[at]' => '[at]', '{at}' => '{at}', '/AT/' => '/AT/')); ?>
		
		<!-- hyperlinks !-->
		<p><?php _e('Should E-Mail-Addresses clickable ? (mailto:youremail@example.com)'); ?><br />
		<?php _e('Cryptex provides an integrated key-shifting based encryption/decryption of hyperlinks to ensure maximum protection.'); ?>
		</p>
		<?php $this->_settingsUtility->displayCheckbox('Enable-Hyperlinks', 'enable-hyperlink'); ?>
		
		<!-- EMail Security Level -->
		<p><?php _e('E-Mail-Addresses can be displayed as an single image or in case of higher security as an hybrid-image.'); ?><br />
		<?php _e('The address will be splitted into 2 parts (before and after the @ sign). Each part is displayed as a single image, the at sign as plain text. This feature provides an improved protection against ocr-grabbing spambot, which will analyze single page images. '); ?><br />
		<?php _e('Note: This option will only influence E-Mail-Addresses, other content will be still displayed as a single image!'); ?>
		</p>
		<?php $this->_settingsUtility->displaySelect('E-Mail Security Level', 'security-level', array('Single Image' => '1', 'Hybrid Image (2 Images, seperated by @ sign)' => '2')); ?>
		
	</div>
	
	<!-- offsets !-->
    <h3><?php _e('Image Offsets'); ?></h3>
    <div class="CryptexBlockcontent">
 		<!-- Image Offsets -->
		<p><?php _e('Sometimes the generated text, depending on the selected font family, won`t fit into his image box - it is possible to configure the following offsets (in px) to fix this issue:')?><br />
		<?php _e('Offsets can also be used to adjust the font baseline (use OffsetA and OffsetB).'); ?>
		</p>
		<p><img src="<?php echo plugins_url('/cryptex/resources/admin/offsets.png'); ?>" alt="offsets" /></p>
		<?php $this->_settingsUtility->displayInput('OffsetX (width)', 'offset-x', 'e.g. 5'); ?>
		<?php $this->_settingsUtility->displayInput('OffsetY (height)', 'offset-y', 'e.g. 5'); ?>
		<?php $this->_settingsUtility->displayInput('OffsetA (font position x)', 'offset-a', 'e.g. 2'); ?>
		<?php $this->_settingsUtility->displayInput('OffsetB (font position y)', 'offset-b', 'e.g. 2'); ?>   
    </div>
	
	<!-- CDN SETTINGS -->
	<h3><?php _e('CDN (Content Delivery Network)'); ?></h3>
	<div class="CryptexBlockcontent">		
		<p><?php _e('These options might be required when using a Content-Delivery-Network (CDN) or another server/location which outsources your CSS+Javascript files.'); ?><br />
		<?php _e('In this case you have to manually include Cryptex.js and Cryptex.css into your page!'); ?><br />
		<?php _e('The generated styles are'); ?> <a href="<?php echo plugins_url('/cryptex/cache/Cryptex.css') ?>"><?php _e('available here'); ?></a> (cryptex/cache/Cryptex.css).</p>
		
		<!-- embed css !-->
		<?php $this->_settingsUtility->displayCheckbox('Include Cryptex-CSS', 'embed-css') ?>
	
		<!-- embed JS !-->
		<?php $this->_settingsUtility->displayCheckbox('Include Cryptex-Javascript', 'embed-js'); ?>

	</div>
	
	<!-- ADVANCED SETTINGS -->
	<h3><?php _e('Advanced'); ?></h3>
	<p><strong><?php _e('Warning: These options are for advanced users only!'); ?></strong></p>
	<div class="CryptexBlockcontent">
		<p><?php _e('Should the shortcode [email] added as alias for cryptex ? This may can influence other plugins because of identical names!'); ?></p>
		<!-- email shortcode !-->
		<?php $this->_settingsUtility->displayCheckbox('Use [email] Shortcode', 'shortcode-email') ?>
	
		<!-- css prefix -->
		<p><?php _e('An optional prefix added to the generated css classes to match your content-container and retain cryptex styles.'); ?></p>
		<?php $this->_settingsUtility->displayInput('CSS Prefix', 'css-prefix', 'e.g. #content, .mycontentarea'); ?>
		
		<!-- css classes -->
		<p><?php _e('Additional css classes added to the outer span-tag - maybe used to add icons.')?></p>
		<?php $this->_settingsUtility->displayInput('Additional Classes', 'css-classes', 'e.g. email mailicon'); ?>
		
		<!-- font filenames -->
		<p><?php _e('Should the full font-paths be displayed on this settings page or only their filenames ?')?></p>
		<?php $this->_settingsUtility->displayCheckbox('Show full font-paths', 'show-full-paths') ?>

	</div>
	
	
	<!-- submit !-->
    <?php submit_button(); ?>

</form>

<h3><?php _e('Credits') ?></h3>
<p><a href="http://www.a3non.org/go/cryptex">Cryptex</a> is developed by <a href="http://andidittrich.de">Andi Dittrich</a>. It's release under the MIT X11 License. Includes: <a href="http://www.eyecon.ro/colorpicker/">Colorpicker</a> by <a href="http://www.eyecon.ro">Stefan Petre</a> - MIT/GPL License</p>
</div>
