<?php if (!defined('CRYPTEX_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>
<?php add_thickbox(); ?>

<!-- CryptexSettings:wrap -->
<div class="wrap" id="cryptex-settings">

<!-- Settings Tabs -->
<h2 class="nav-tab-wrapper" id="cryptex-tabnav">
    <a data-tab="CryptexTabAppearance" class="nav-tab"><?php _e('Appearance', 'cryptex'); ?></a>
    <a data-tab="CryptexTabImages" class="nav-tab"><?php _e('Images', 'cryptex'); ?></a>
    <a data-tab="CryptexTabShortcodes" class="nav-tab"><?php _e('Shortcodes', 'cryptex'); ?></a>
    <a data-tab="CryptexTabAutodetection" class="nav-tab"><?php _e('Autodetection', 'cryptex'); ?></a>
    <a data-tab="CryptexTabFonts" class="nav-tab"><?php _e('Fonts', 'cryptex'); ?></a>
    <a data-tab="CryptexTabOptions" class="nav-tab"><?php _e('Options', 'cryptex'); ?></a>
    <a data-tab="CryptexTabExtensions" class="nav-tab"><?php _e('Extensions', 'cryptex'); ?></a>
</h2>

<!-- Main Title -->
<h1 class="maintitle"><span class="cryptex-title-badge"></span><?php echo CRYPTEX_PLUGIN_TITLE; ?></h1>
<p><?php echo CRYPTEX_PLUGIN_HEADLINE; ?></p>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('cryptex-settings-group' ); ?>
    <!-- #poststuff -->
    <div id="poststuff">

<!-- 2 Column Layout -->
<div id="post-body" class="metabox-holder columns-2">
    <div id="post-body-content">
     
        <div id="CryptexTabAppearance">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Appearance.phtml'); ?>
        </div>

        <div id="CryptexTabImages">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Images.phtml'); ?>
        </div>

        <div id="CryptexTabShortcodes">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Shortcodes.phtml'); ?>
        </div>

        <div id="CryptexTabAutodetection">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Autodetection.phtml'); ?>
        </div>

        <div id="CryptexTabFonts">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Fonts.phtml'); ?>
        </div>
        
        <div id="CryptexTabOptions">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Options.phtml'); ?>
        </div>

        <div id="CryptexTabExtensions">
        <?php require (CRYPTEX_PLUGIN_PATH.'/views/admin/Extensions.phtml'); ?>
        </div>
        
        <!-- submit !-->
        <?php submit_button(); ?>

    </div>
    <!-- // MAIN COLUMN -->
    
    <!-- Right Column -->
    <div id="postbox-container-1" class="postbox-container">
        <?php require(CRYPTEX_PLUGIN_PATH.'/views/admin/SystemInfo.phtml'); ?>
        
        <?php require(CRYPTEX_PLUGIN_PATH.'/views/admin/Related.phtml'); ?>
    </div>
    <!-- // Right Column -->
    
</div>
<!-- // 2 Column Layout -->

</div>
<!-- // #poststuff -->

</form>
<div class="clear"></div>
<hr />
<p class="credits">
    <a href="https://github.com/AndiDittrich/WordPress.Cryptex/">Cryptex</a> <?php _e('is developed by', 'cryptex'); ?> <a href="https://andidittrich.de">Andi Dittrich</a>.
    <?php printf(__('It`s released under the terms of the %s', 'cryptex'), '<a href="#TB_inline?width=800&height=550&inlineId=cryptex-license" class="thickbox">'.__('GPL-2.0', 'cryptex').'</a>'); ?><br />
    <strong><?php _e('Includes:', 'cryptex'); ?></strong> <a href="http://www.eyecon.ro/colorpicker/">Colorpicker</a> <?php _e('by', 'cryptex'); ?> <a href="http://www.eyecon.ro">Stefan Petre</a> - MIT/GPL <?php _e('License', 'cryptex'); ?>
    | <a href="https://fedorahosted.org/liberation-fonts/">Liberation(tm) Fonts</a> SIL Open Font License, Version 1.1
    | <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> <?php _e('by', 'cryptex'); ?> <a href="https://andidittrich.de">Andi Dittrich</a> - MPL 2.0 <?php _e('License', 'cryptex'); ?>;
</p>
<hr />

<?php require(CRYPTEX_PLUGIN_PATH.'/views/admin/License.phtml'); ?>

</div>
<!-- // CryptexSettings:wrap -->

<div class="clear"></div>